export const mockProductList = [
    {
        id: '1',
        name: 'Đồng hồ Rolex Submariner',
        size: '40mm',
        material: 'Thép không gỉ',
        caseMaterial: 'Thép không gỉ 316L',
        strapMaterial: 'Dây cao su tự nhiên',
        strapColor: 'Đen',
        diameter: '40mm',
        thickness: '12mm',
        waterResistance: '100m',
        movement: 'Automatic Nhật Bản',
        dialColor: 'Xanh dương',
        price: '490.000 đ',
        originalPrice: '1.100.000 đ',
        description: 'Đồng hồ cao cấp với thiết kế sang trọng, phù hợp cho mọi dịp.',
        mainImage: '/1.jpeg',
        subImages: ['/2.jpeg', '/3.jpeg', '/4.jpeg']
    },
    {
        id: '2',
        name: 'Đồng hồ Casio Edifice',
        size: '42mm',
        material: 'Thép không gỉ',
        caseMaterial: 'Thép không gỉ',
        strapMaterial: 'Dây kim loại',
        strapColor: 'Bạc',
        diameter: '42mm',
        thickness: '11mm',
        waterResistance: '50m',
        movement: 'Quartz Nhật Bản',
        dialColor: 'Đen',
        price: '850.000 đ',
        originalPrice: '1.500.000 đ',
        description: 'Thiết kế thể thao mạnh mẽ, phù hợp cho nam giới hiện đại.',
        mainImage: '/casio1.jpeg',
        subImages: ['/casio2.jpeg', '/casio3.jpeg', '/casio4.jpeg']
    },
    {
        id: '3',
        name: 'Đồng hồ Daniel Wellington',
        size: '36mm',
        material: 'Thép không gỉ mạ vàng',
        caseMaterial: 'Thép mạ PVD',
        strapMaterial: 'Dây da thật',
        strapColor: 'Nâu',
        diameter: '36mm',
        thickness: '6mm',
        waterResistance: '30m',
        movement: 'Quartz Thụy Điển',
        dialColor: 'Trắng',
        price: '990.000 đ',
        originalPrice: '2.300.000 đ',
        description: 'Phong cách tối giản, thanh lịch dành cho phái nữ.',
        mainImage: '/dw1.jpeg',
        subImages: ['/dw2.jpeg', '/dw3.jpeg', '/dw4.jpeg']
    },
    {
        id: '4',
        name: 'Đồng hồ Seiko 5',
        size: '39mm',
        material: 'Thép không gỉ',
        caseMaterial: 'Thép không gỉ 316L',
        strapMaterial: 'Dây kim loại',
        strapColor: 'Bạc',
        diameter: '39mm',
        thickness: '13mm',
        waterResistance: '100m',
        movement: 'Automatic Nhật Bản',
        dialColor: 'Xanh lá',
        price: '1.290.000 đ',
        originalPrice: '2.800.000 đ',
        description: 'Đồng hồ cơ lộ máy nổi bật với mặt kính Hardlex độc quyền.',
        mainImage: '/seiko1.jpeg',
        subImages: ['/seiko2.jpeg', '/seiko3.jpeg', '/seiko4.jpeg']
    },
    {
        id: '5',
        name: 'Đồng hồ Tissot PRX',
        size: '40mm',
        material: 'Thép không gỉ cao cấp',
        caseMaterial: 'Thép không gỉ',
        strapMaterial: 'Dây kim loại',
        strapColor: 'Bạc',
        diameter: '40mm',
        thickness: '10.5mm',
        waterResistance: '100m',
        movement: 'Automatic Thụy Sĩ',
        dialColor: 'Xanh navy',
        price: '3.990.000 đ',
        originalPrice: '6.500.000 đ',
        description: 'Thiết kế thập niên 70 cổ điển, được yêu thích bởi tín đồ đồng hồ.',
        mainImage: '/tissot1.jpeg',
        subImages: ['/tissot2.jpeg', '/tissot3.jpeg', '/tissot4.jpeg']
    }
];